library(shiny)
library(colourpicker)

# Define UI for application that draws a histogram
shinyUI(fluidPage(

  # Application title
  titlePanel(
    h1("INDIA Tourism 2014-2020 Dataset")
  ),

  # Sidebar with a slider input for number of bins
  sidebarLayout(
    sidebarPanel(
      h3("Evolution of Annual Visitors"),
      selectInput(inputId = "country1",
                  label = "Select Country 1",
                  choices = list("Canada" = "Canada",
                                 "U.S.A" = "U.S.A",
                                 "Argentina" = "Argentina",
                                 "Brazil" = "Brazil",
                                 "Mexico" = "Mexico",
                                 "Austria" = "Austria",
                                 "Belgium" = "Belgium",
                                 "Denmark" = "Denmark",
                                 "Finland" = "Finland",
                                 "France" = "France",
                                 "Germany" = "Germany",
                                 "Greece" = "Greece",
                                 "Ireland" = "Ireland",
                                 "Italy" = "Italy",
                                 "Netherlands" = "Netherlands",
                                 "Norway" = "Norway",
                                 "Portugal" = "Portugal",
                                 "Spain" = "Spain",
                                 "Sweden" = "Sweden",
                                 "Switzerland" = "Switzerland",
                                 "U.K." = "U.K.",
                                 "Czech Rep." = "Czech Rep.",
                                 "Hungary" = "Hungary",
                                 "Kazakhstan" = "Kazakhstan",
                                 "Poland" = "Poland",
                                 "Russian Fed" = "Russian Fed",
                                 "Ukraine" = "Ukraine",
                                 "Egypt" = "Egypt",
                                 "Kenya" = "Kenya",
                                 "Mauritius" = "Mauritius",
                                 "Nigeria" = "Nigeria",
                                 "South Africa" = "South Africa",
                                 "Sudan" = "Sudan",
                                 "Tanzania" = "Tanzania",
                                 "Bahrain" = "Bahrain",
                                 "Iraq" = "Iraq",
                                 "Israel" = "Israel",
                                 "Oman" = "Oman",
                                 "Saudi Arabia" = "Saudi Arabia",
                                 "Turkey" = "Turkey",
                                 "U.A.E." = "U.A.E.",
                                 "Yemen Arab Rep." = "Yemen Arab Rep.",
                                 "Afghanistan" = "Afghanistan",
                                 "Bangladesh" = "Bangladesh",
                                 "Bhutan" = "Bhutan",
                                 "Iran" = "Iran",
                                 "Maldives" = "Maldives",
                                 "Nepal" = "Nepal",
                                 "Pakistan" = "Pakistan",
                                 "Sri Lanka" = "Sri Lanka",
                                 "Indonesia" = "Indonesia",
                                 "Malaysia" = "Malaysia",
                                 "Myanmar" = "Myanmar",
                                 "Philippines" = "Philippines",
                                 "Singapore" = "Singapore",
                                 "Thailand" = "Thailand",
                                 "Vietnam" = "Vietnam",
                                 "China" = "China",
                                 "Japan" = "Japan",
                                 "Rep. of Korea" = "Rep. of Korea",
                                 "Taiwan" = "Taiwan",
                                 "Australia" = "Australia",
                                 "New Zealand" = "New Zealand"),
                  selected =  "Canada"),
      selectInput(inputId = "country2",
                  label = "Select Country 2",
                  choices = list("Canada" = "Canada",
                                 "U.S.A" = "U.S.A",
                                 "Argentina" = "Argentina",
                                 "Brazil" = "Brazil",
                                 "Mexico" = "Mexico",
                                 "Austria" = "Austria",
                                 "Belgium" = "Belgium",
                                 "Denmark" = "Denmark",
                                 "Finland" = "Finland",
                                 "France" = "France",
                                 "Germany" = "Germany",
                                 "Greece" = "Greece",
                                 "Ireland" = "Ireland",
                                 "Italy" = "Italy",
                                 "Netherlands" = "Netherlands",
                                 "Norway" = "Norway",
                                 "Portugal" = "Portugal",
                                 "Spain" = "Spain",
                                 "Sweden" = "Sweden",
                                 "Switzerland" = "Switzerland",
                                 "U.K." = "U.K.",
                                 "Czech Rep." = "Czech Rep.",
                                 "Hungary" = "Hungary",
                                 "Kazakhstan" = "Kazakhstan",
                                 "Poland" = "Poland",
                                 "Russian Fed" = "Russian Fed",
                                 "Ukraine" = "Ukraine",
                                 "Egypt" = "Egypt",
                                 "Kenya" = "Kenya",
                                 "Mauritius" = "Mauritius",
                                 "Nigeria" = "Nigeria",
                                 "South Africa" = "South Africa",
                                 "Sudan" = "Sudan",
                                 "Tanzania" = "Tanzania",
                                 "Bahrain" = "Bahrain",
                                 "Iraq" = "Iraq",
                                 "Israel" = "Israel",
                                 "Oman" = "Oman",
                                 "Saudi Arabia" = "Saudi Arabia",
                                 "Turkey" = "Turkey",
                                 "U.A.E." = "U.A.E.",
                                 "Yemen Arab Rep." = "Yemen Arab Rep.",
                                 "Afghanistan" = "Afghanistan",
                                 "Bangladesh" = "Bangladesh",
                                 "Bhutan" = "Bhutan",
                                 "Iran" = "Iran",
                                 "Maldives" = "Maldives",
                                 "Nepal" = "Nepal",
                                 "Pakistan" = "Pakistan",
                                 "Sri Lanka" = "Sri Lanka",
                                 "Indonesia" = "Indonesia",
                                 "Malaysia" = "Malaysia",
                                 "Myanmar" = "Myanmar",
                                 "Philippines" = "Philippines",
                                 "Singapore" = "Singapore",
                                 "Thailand" = "Thailand",
                                 "Vietnam" = "Vietnam",
                                 "China" = "China",
                                 "Japan" = "Japan",
                                 "Rep. of Korea" = "Rep. of Korea",
                                 "Taiwan" = "Taiwan",
                                 "Australia" = "Australia",
                                 "New Zealand" = "New Zealand"),
                  selected =  "U.S.A"),
      a(
        href = "https://www.kaggle.com/datasets/rajkachhadiya/india-tourism-20142020",
        h5("INDIA Tourism 2014-2020 Dataset"))
    ),

    mainPanel(
      plotOutput("linePlot",
                 click = "plot_click",
                 dblclick = dblclickOpts(id = "plot_dblclick")
      ),

      fluidRow(
        column(width = 6,
               verbatimTextOutput("click_info")
        ),
        column(width = 6,
               verbatimTextOutput("dblclick_info")
        ),

        fluidPage(
          plotOutput("plot")
        )
      )
    )
  )))
